Instrucciones y guías
PTSD-3D/PTSD-Engine pull request #14
Opened 2021-03-26 11:15 UTC by EstebenR

Ahora el gobierno es centralizado 🐍 🐍

2021-03-26 18:01 UTC, Drathijin requested changes
precioso

2021-03-26 18:01 UTC, Drathijin approved these changes
he dicho precioso

2021-03-27 11:27 UTC, AdriAlvarez00 approved these changes
Y mete lo de los tabs

2021-03-28 12:29 UTC, Adrian-de-Lucas-Gomez approved these changes
Como gusta el tener las cosas organizaditas

2021-03-28 12:29 UTC, merged