Inicialización e interfaz de gráficos
PTSD-3D/PTSD-Engine pull request #18
Opened 2021-03-30 09:38 UTC by AdriAlvarez00

Todo esta en main.cpp y lod métodos están comentados

2021-03-30 20:31 UTC, Adrian-de-Lucas-Gomez approved these changes
Chachi pistachi el cabezón de Ogre

2021-03-31 11:29 UTC, EstebenR requested changes
Desaparecio el sound?

2021-03-31 12:26 UTC, EstebenR approved these changes
Ya va el sound

poletti momento

2021-03-31 14:46 UTC, Will7461 approved these changes

2021-03-31 14:46 UTC, merged