Implementacion input
PTSD-3D/PTSD-Engine pull request #20
Opened 2021-03-31 20:55 UTC by evalucas

Está el método test en PTSDInput para comprobar que os lee bien la entrada (teclado, ratón y mando).

2021-03-31 21:19 UTC, EstebenR requested changes
Mejor tener guardado un puntero a la implementacion de input y asi no estar pidiendolo todo el rato; tampoco tiene la implementacion por qué ser un singleton ya que solo la llama la interfaz

Cambiad los nombres con los nuevos guidelines (sin acortamientos)

2021-03-31 21:19 UTC, dagodoy approved these changes
Tira bien, aunque pone "Button down on SYSTEM " cuando aprietas y cuando sueltas

Tiene toda la pinta de que sobra código para lo que vamos a hacer, habría que fusilar métodos

2021-04-01 14:48 UTC, AdriAlvarez00 approved these changes

2021-04-01 15:34 UTC, EstebenR approved these changes
bem

2021-04-01 15:34 UTC, merged