Transform
PTSD-3D/PTSD-Engine pull request #36
Opened 2021-04-12 20:17 UTC by evalucas

El componente Transform está en PTSDCore, a falta de un sitio mejor donde ubicarlo, en los archivos TransformComponent.h/.cpp .
En main.cpp hay código para debuggear los métodos del componente:
- translate 
- rotate
- scale
- getters/setters

Hemos tenido problemas con el parenting, en cuanto a las rotaciones de los transform. Debido a esto de momento no es funcional este apartado, pero será revisado más adelante si es necesario.

Técnicamente tenemos un sinbad bailando.

2021-04-13 08:47 UTC, Drathijin requested changes

2021-04-13 08:47 UTC, Drathijin commented on source/Core/src/main.cpp
> +#include <OgreEntity.h>
Entiendo que esto es para debug, pero tenemos que tener cuidado con incluir implementaciones o cosas de librerias en main. Pasen lo que haga falta a una función del PTSDGraphics, aunque sea para probar... creo que es preferible a tener estas cosillas en el main

2021-04-14 08:23 UTC, mmur07 requested changes
Esto creo que mejor dejarlo como estaba

2021-04-14 13:22 UTC, Drathijin commented
> Esto creo que mejor dejarlo como estaba

te refieres a con el include de Ogre en main? Podemos dejarlo así.. pero hay que recordar quitar de ahí los includes en cuanto saquemos las cositas de la malla a su función.

2021-04-14 13:26 UTC, Drathijin approved these changes
hay conflictos con main, pero por mí está bien :+1:

2021-04-14 15:40 UTC, AdriAlvarez00 approved these changes
Let's a go

2021-04-14 15:44 UTC, mmur07 approved these changes

2021-04-14 15:44 UTC, merged