Modelo nave jugador
PTSD-3D/PTSD-Engine pull request #45
Opened 2021-04-25 20:14 UTC by Adrian-de-Lucas-Gomez

Tiene las texturitas muy chachis. He hecho un modelo un poco mas refinado al original pero con la misma base pero ahora usa textura para darle color en vez de materiales.

2021-04-26 07:45 UTC, AdriAlvarez00 requested changes
Esta guay pero esto va al repo de Tai-Fighter
No se si es mi pc pero se ve un poco borrosa, seguiste el consejo de Álvar?
![imagen](https://user-images.githubusercontent.com/48672128/116047224-26a9a000-a674-11eb-801b-ea422c466b70.png)

2021-04-26 08:50 UTC, EstebenR requested changes
Si no hay fix para las normales y las sombras va a haber que hacer los modelos de otra manera o fixearlos manualmente en blender

2021-04-29 08:22 UTC, AdriAlvarez00 approved these changes
Nice, pero subelo a taifighter tb

2021-04-30 10:51 UTC, EstebenR requested changes
Espectacular la navecita owo

Ya va bien, revisa que no haya archivos sobrantes, que creo que Untitled.mesh y Voxel.mesh no se usan, si sobran borralos

2021-04-30 10:52 UTC, EstebenR approved these changes
Espectacular la navecita owo

Ya va bien, revisa que no haya archivos sobrantes, que creo que Untitled.mesh y Voxel.mesh no se usan, si sobran borralos

2021-04-30 12:13 UTC, evalucas approved these changes
To guachi la navecita

2021-04-30 12:31 UTC, merged