Blender script update
PTSD-3D/PTSD-Engine pull request #50
Opened 2021-04-28 06:14 UTC by Drathijin

En _"Assets/Client/Prefabs"_ hay un prefab y una configuración de escena. El nombre de los objetos de blender tiene que coincidir con el de su prefab. Y si se quiere usar un objeto de configuración de escena se tiene que guradar en un .lua del tipo _"nombreDeEscena-config.lua"_, por defecto se busca en el mismo directorio que los prefabs. 
Si no se quiere hacer un archivo de configuración siempre se puede cambiar la parte del script que pone un string cuando no se encuentra el archivo.

2021-04-28 15:46 UTC, Auraum approved these changes
Guay pero tiene conflictos

2021-04-28 15:48 UTC, Pj6595 approved these changes

2021-04-28 16:15 UTC, EstebenR requested changes
No compila, no se traga el entry.path it seems, lo demás bien

bueno tambien indentas raro

2021-04-29 05:20 UTC, Drathijin commented
> No compila, no se traga el entry.path it seems, lo demás bien
> 
> bueno tambien indentas raro

No se a que te refieres con el entry.path, no compilaba por el merge con tu pull request que se cambiaron cosas del lua. Ahora debería de funcionar bien. 

Meti un code formatter para lua en VSCode (el uno que he visto que funcione con tabs es **luafmt** por si quieren usar el mismo)

2021-04-29 09:31 UTC, EstebenR approved these changes

2021-04-29 09:33 UTC, merged