Collision
PTSD-3D/PTSD-Engine pull request #60
Opened 2021-05-07 04:37 UTC by Drathijin

# Colisiones
He modificado el código de btOgre para que guarde nuestras IDs de entidades en los CollisionListeners y cambiando el orden de guardado del user_pointer para que ocurra cuando existan las entidades con las ids (en el init del componente).
El script_manager como no es un singleton necesita llamar al singleton de físicas durante la inicialización para guardar referencia al scriptManager, así avisamos de las colisiones.

## Como se usa
``` lua
function miclase:initialize()
  Manager.eventManager:addListener("CollisionEv", self, self.miCallbackDeColision)
end

function miclase:miCallbackDeColision(ev)
  --...
  --Lo que quieras aquí ^^
end
```
Y ya estaría :D

## Por ahora el evento tiene
- ID entidad A
- ID entidad B
- Manifold {Punto de colision A, Punto de colision B}

## Extras
- También he cambiado cosas del _build.bash_ pero solo afectan a Linux así que lo he pusheado aquí.
- He cambiado un poco el bullet system para no borrar las balas y hacer cosillas cuando acaba su tiempo de vida y colisionan
- He arreglado un bug que creaba dos entidades en la escena en lugar de una (esto era lo que creía que detectaba el input dos veces)

2021-05-07 21:40 UTC, Drathijin commented
He cambiado como se monta. Ahora con añadir una función onCollision a un sistema tienes todo hookeado. Se llama solo si importa la colision con la entidad en el sistema y se manda un array de puntos de colision junto con ambas entidades.

El BulletSystem está de ejmplo:
```lua
function BulletSystem:onCollision(ent, other, col)
	ent.Mesh:setMaterial("Red")
	other.Mesh:setMaterial("Red")
	ent.Transform:translate(vec3:new(self.factor*math.random(1),self.factor*math.random(1),self.factor*math.random(1)))
	other.Transform:translate(vec3:new(self.factor*-1*math.random(1),self.factor*-1*math.random(1),self.factor*-1*math.random(1)))
	print("Collision Points:")
	for i,v in ipairs(col) do
		v:print("\t"..i..": ") --Esto es solo para imprimir mejor los puntos de colision
	end	
	self.factor = self.factor+1
end
```

2021-05-08 17:46 UTC, mmur07 approved these changes

2021-05-08 17:51 UTC, Pj6595 approved these changes

2021-05-08 17:57 UTC, EstebenR requested changes
pido rev

2021-05-09 10:06 UTC, EstebenR approved these changes
Bien, queda pendiente quitar toda la vaina del bulletSystem

2021-05-09 10:07 UTC, merged