CEGUI existe
PTSD-3D/PTSD-Engine pull request #7
Opened 2021-03-22 22:12 UTC by aitorcrok

Proyecto montado, CEGUI funciona en el proyecto

INSTRUCCIONES CMAKE DE CEGUI

1) Se hace Cmake con PTSD-Engine\dependencies\CEGUI\src como source, y una carpeta "build" como salida (Hacer 2 veces el configure porque Cmake)
2) Se marca la casilla de CEGUI_BUILD_RENDERER_OGRE
3) Tras configurar, buscar con la casilla Advanced marcada "Ogre"
4) En ruta absoluta, en OGRE_H_BUILD_SETTINGS_PATH: PTSD-Engine\dependencies\Ogre\build\include
5) En ruta absoluta, en OGRE_H_PATH: PTSD-Engine\dependencies\Ogre\src\include
6) En ruta absoluta, en OGRE_LIB: PTSD-Engine\dependencies\Ogre\build\lib\Release\OgreMain.lib
7) En ruta absoluta, en OGRE_LIB_DBG: PTSD-Engine\dependencies\Ogre\build\lib\Debug\OgreMain_d.lib

#Es posible que cmake de un error a la hora de generar los archivos y no pueda generarlos
#probad cada uno porque depende de la persona

8) Tras generar, buscar el archivo Config.h en PTSD-Engine\dependencies\CEGUI\build\cegui\include\CEGUI y buscar "ogre". Dejar esta parte con los numeros que siguen
```

#ifndef CEGUI_OGRE_VERSION_MAJOR
#   define CEGUI_OGRE_VERSION_MAJOR 1
#endif
#ifndef CEGUI_OGRE_VERSION_MINOR
#   define CEGUI_OGRE_VERSION_MINOR 12
#endif
#ifndef CEGUI_OGRE_VERSION_PATCH
#   define CEGUI_OGRE_VERSION_PATCH 11
#endif
#ifndef CEGUI_OGRE_VERSION
#   define CEGUI_OGRE_VERSION ((CEGUI_OGRE_VERSION_MAJOR << 16) | (CEGUI_OGRE_VERSION_MINOR << 8) | CEGUI_OGRE_VERSION_PATCH)
#endif
```
#Es posible que no de error el paso 9, en ese caso ya has terminado
9) Compilar en Visual. Dará un error. Buscar Ogre::Image::Box, cambiarlo a Ogre::Box
10) Compilar de nuevo. No debería dar errores ya

2021-03-23 09:47 UTC, AdriAlvarez00 approved these changes
Guay, pero deberiamos guardar el tutorial en un txt y añadir ejecutar el .bat para copiar

2021-03-23 09:59 UTC, EstebenR submitted a review, later dismissed
Va bene

2021-03-23 10:02 UTC, AdriAlvarez00 approved these changes
Working as intended

2021-03-24 12:39 UTC, EstebenR requested changes
Falta el txt de instrucciones

2021-03-24 13:01 UTC, EstebenR submitted a review, later dismissed
guay

2021-03-24 13:56 UTC, AdriAlvarez00 approved these changes
Quitamos lo del auto dismiss?

2021-03-24 15:19 UTC, Pj6595 submitted a review, later dismissed
Very nice, me da miedo mergear por los conflicts 👯‍♂️

2021-03-25 10:25 UTC, EstebenR approved these changes
Va bene

2021-03-25 10:51 UTC, AdriAlvarez00 approved these changes
Buen merge

2021-03-25 12:12 UTC, Drathijin approved these changes
Me funciona buildear en Linux así que like :+1:

2021-03-25 12:18 UTC, Drathijin commented
Acabo de resolver los conflictos pero como eran con el proyecto de Visual no puedo comprobar si va bien. Estoy bastante seguro de que va. Que alguien lo compruebe, alguien que ya tenga los binarios de CEGUI para que solo sea buildear en visual. Y si funciona pues que hagan el Squash and merge :slightly_smiling_face:

2021-03-25 16:55 UTC, merged